FROM node:20-alpine AS dev

# Dossier de travail dans le conteneur
WORKDIR /app

# Copier uniquement les fichiers de dépendances pour l’installation
COPY package*.json ./

# Installer les dépendances
RUN --mount=type=cache,target=/root/.npm npm install

# Copier tout le reste (sauf si on monte le code via volumes)
COPY . .

# Exposer le port utilisé par Vite (par défaut : 5173)
EXPOSE 5173

# Démarrer Vite en mode développement
CMD ["npm", "run", "dev"]
