FROM node:20-alpine

RUN apk add --no-cache bash

WORKDIR /app

# Copie uniquement les fichiers nécessaires pour l’installation
COPY package*.json ./

# Installe toutes les dépendances (dev + prod)
RUN npm install

# Copie le reste du code (sauf si tu utilises volumes)
COPY . .

# Expose le port du serveur
EXPOSE 5010

# Lancer le projet en mode dev (avec ts-node-dev)
CMD ["npm", "run", "dev"]
